name: Download Image
on:
  workflow_dispatch:
    inputs:
      image_url:
        description: 'Image URL to download'
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install node-fetch
      - name: Download image
        run: node scripts/download.js "${{ github.event.inputs.image_url }}"
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add public/
          git commit -m "Add new image" || exit 0
          git push
